import JSZip from 'jszip'

export async function buildSiteZip(html: string, businessName: string): Promise<Buffer> {
  const zip = new JSZip()

  // Extract all Unsplash image URLs from the HTML
  const unsplashRegex = /https:\/\/images\.unsplash\.com\/[^"'\s)]+/g
  const matches = [...new Set(html.match(unsplashRegex) ?? [])]

  let processedHtml = html
  const imagesFolder = zip.folder('images')!

  // Download each image and replace URL with relative path
  await Promise.all(
    matches.map(async (url, index) => {
      try {
        const response = await fetch(url)
        if (!response.ok) return
        const arrayBuffer = await response.arrayBuffer()
        const filename = `image-${index + 1}.jpg`
        imagesFolder.file(filename, arrayBuffer)
        processedHtml = processedHtml.replaceAll(url, `./images/${filename}`)
      } catch {
        // Keep original URL if fetch fails
      }
    })
  )

  // Add a simple README
  zip.file(
    'README.txt',
    `${businessName} - Landing Page\n\nGenerated by PageCraft AI\n\nFiles:\n- index.html: Your complete landing page\n- images/: All images used on your page\n\nTo launch your site:\n1. Upload all files to your web hosting\n2. Make sure to upload the images/ folder too\n3. Open index.html in a browser to preview locally\n\nFonts are loaded from Google Fonts (requires internet connection).\n\nEnjoy your new website! 🚀`
  )

  zip.file('index.html', processedHtml)

  const buffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' })
  return buffer
}
